#-------------------------------------------------------------------------------
# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome
 # Comment to be posted to on first time issues
newIssueWelcomeComment: >
   Thanks for opening this issue. A contributor will be by to give feedback soon. In the meantime, please review the [Meshery Community Welcome Guide](https://meshery.io/community) and sure to join the [community Slack](https://slack.meshery.io/).
 # Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome
 # Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
   Yay, your first pull request! :thumbsup: A contributor will be by to give feedback soon. In the meantime, please review the [Meshery Community Welcome Guide](https://meshery.io/community) and sure to join the [community Slack](https://slack.meshery.io/).

   Be sure to double-check that you have signed your commits. Here are instructions for [making signing an implicit activity while peforming a commit](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin).


#-------------------------------------------------------------------------------
# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge
# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
   &nbsp; &#9; &nbsp; &#9;  &nbsp; &#9;  &nbsp; &#9; Thank you for contributing to the Meshery community! :tada:
  \
  \
  <picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://raw.githubusercontent.com/meshery/meshery.io/master/.github/welcome/Meshery-celebration-dark.svg">
  <source media="(prefers-color-scheme: light)" srcset="https://raw.githubusercontent.com/meshery/meshery.io/master/.github/welcome/Meshery-celebration-light.svg">
  <img alt="Shows a black logo in light color mode and a white one in dark color mode." src="https://user-images.githubusercontent.com/25423296/163456779-a8556205-d0a5-45e2-ac17-42d089e3c3f8.png">
</picture>
  \
  \
  &nbsp; &#9; &nbsp; &#9;  &nbsp; &#9;  &nbsp; &#9; :star: Please leave a [star on the project](../stargazers). :smile:


#-------------------------------------------------------------------------------
# Configuration for request-info - https://github.com/behaviorbot/request-info
# Comment to reply with
requestInfoReplyComment: >
  Thanks for opening this issue. We welcome all input! If you could provide a little more information, this will greatly aide in its resolution. :thumbsup:
# *OPTIONAL* Add a list of people whose Issues/PRs will not be commented on
# keys must be GitHub usernames
#requestInfoUserstoExclude:
#  - meshery/maintainers


#-------------------------------------------------------------------------------
# Configuration for sentiment-bot - https://github.com/behaviorbot/sentiment-bot
# *Required* toxicity threshold between 0 and .99 with the higher numbers being the most toxic
# Anything higher than this threshold will be marked as toxic and commented on
sentimentBotToxicityThreshold: .9

# *Required* Comment to reply with
sentimentBotReplyComment: >
  Please be sure to review the code of conduct and be respectful of other users. // @meshery/maintainers 
  
